In [14]:
import tensorflow as tf
import numpy as np

In [18]:
# np.array() - array생성
# np.ndim - 차원 확인
# x.shape - shape 확인

In [15]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)
print(np.ndim(x))

(2, 3)
2


In [17]:
a = np.zeros((10,10))
print(a)
b = np.ones((10,10))
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
# np.full((차원,차원,차원,차원),채울값)
# np.eye() - diagnal 1로 채운다

In [24]:
c = np.full((3,3,3),3)
print(c)
d = np.eye(3)
print(d)
# 5*3  x 3*1 = 5 * 1
# exp, log, 편미분(사용할 줄은 알아야한다)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# np.random.random((차원,차원)) 을 채우는 랜덤값이 나온다.
# np.linsspace(시작,끝,균일등분) --> x축으로 보통 쓰고, 등분을 크게하면 부드러운 그래프를 그릴 수 있다.

# tf.random도 있다. 분포에 따른 랜덤넘버도 있다. 
# normal(평균에 가까운 값이 나올 확률이 높다), standard deviation 퍼져있는 정도 표준편차 stddev
# uniform(모든숫자나올확률 같다)


In [26]:
np.random.random((3,3))

array([[0.52545421, 0.68333688, 0.88725206],
       [0.05946037, 0.22474811, 0.15014021],
       [0.23203014, 0.15027581, 0.88852727]])

In [28]:
np.linspace(0,20,200)

array([ 0.        ,  0.10050251,  0.20100503,  0.30150754,  0.40201005,
        0.50251256,  0.60301508,  0.70351759,  0.8040201 ,  0.90452261,
        1.00502513,  1.10552764,  1.20603015,  1.30653266,  1.40703518,
        1.50753769,  1.6080402 ,  1.70854271,  1.80904523,  1.90954774,
        2.01005025,  2.11055276,  2.21105528,  2.31155779,  2.4120603 ,
        2.51256281,  2.61306533,  2.71356784,  2.81407035,  2.91457286,
        3.01507538,  3.11557789,  3.2160804 ,  3.31658291,  3.41708543,
        3.51758794,  3.61809045,  3.71859296,  3.81909548,  3.91959799,
        4.0201005 ,  4.12060302,  4.22110553,  4.32160804,  4.42211055,
        4.52261307,  4.62311558,  4.72361809,  4.8241206 ,  4.92462312,
        5.02512563,  5.12562814,  5.22613065,  5.32663317,  5.42713568,
        5.52763819,  5.6281407 ,  5.72864322,  5.82914573,  5.92964824,
        6.03015075,  6.13065327,  6.23115578,  6.33165829,  6.4321608 ,
        6.53266332,  6.63316583,  6.73366834,  6.83417085,  6.93

In [29]:
# 배열, linespace만드는 법

In [32]:
# slicing  --  2,3,5,6을 뽑아라

In [31]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
# x[0차원:,1차원:]

In [33]:
print(x[:2,1:])

[[2 3]
 [5 6]]


In [37]:
# 1차원 슬라이싱
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[:])
print(x)
# x[]로 수정하면 x값이 바뀌어버린다.
# x[:] 이렇게해야 복사한것과 같다

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [42]:
# np.arrange(숫자) --> 0부터 숫자가지 배열을 만든다.
# np.arrange(숫자).reshape(4,3)
arr = np.arange(12).reshape(4,3)
print(arr)
row_mean = arr.mean(axis=1).reshape(4,1)
# 빼기하면 브로드캐스팅된다!!!!
k = arr-row_mean
# normalize하는데 쓰이기도한다.
print(k)
# numpy/pandas/matplotlib

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
