In [1]:
import tensorflow as tf
import numpy as np

In [8]:
# constant로 실행하는 법

In [7]:
# 1. 그래프 빌드
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(2.0, tf.float32)
node3 = tf.add(node1,node2)

print(node1, node2, node3)
# 2. 실행
sess = tf.Session()
print(sess.run(node3))
print(sess.run(node1))
print(sess.run(node2))
# 3. 동시에 한 번에 실행 (배열로 실행 가능)
print(sess.run([node1,node2,node3]))

Tensor("Const_10:0", shape=(), dtype=float32) Tensor("Const_11:0", shape=(), dtype=float32) Tensor("Add_5:0", shape=(), dtype=float32)
5.0
3.0
2.0
[3.0, 2.0, 5.0]


In [9]:
# placeholder로 실행하는 법

In [13]:
ph1 = tf.placeholder(tf.float32)
ph2 = tf.placeholder(tf.float32)
adder = ph1 + ph2
print(sess.run(adder,feed_dict={ph1:3, ph2 :4}))
# placeholder명 --> key
print(sess.run(adder,feed_dict={ph1:[3,4,5], ph2 :[4,5,6]}))
# rank = 2 // shape = [2,3]
print(sess.run(adder,feed_dict={ph1:[[3,4,5],[1,2,3]], ph2 :[[4,5,6],[1,2,3]]}))


7.0
[ 7.  9. 11.]
[[ 7.  9. 11.]
 [ 2.  4.  6.]]


In [14]:
# 텐서플로우 디버깅하는법 
# 거꾸로 올라가야한다. 
# 그래프이기때문에 어디가 빵꾸났는지 확인해야한다. 

In [ ]:
# 정규분포에서 10개의 값을 꺼낸다.
# 1시그마를 0.35로 하겟다.
# 초기화를 반드시 해줘야한다. 

In [15]:
v1 = tf.Variable(tf.random_normal([10,10], stddev = 0.35))
# variable을 만들면 반드시 이니셜라이즈해야한다.
sess.run(tf.global_variables_initializer())
# tf.global_variables_initializer() 모든 variable을 초기화 한다. 

In [18]:
# 디버깅용 (하나하나 바로바로 하는 것이다)
sess = tf.InteractiveSession()
t = tf.constant([1,2,3,4])
print(t.eval())

[1 2 3 4]


In [22]:
# t.eval() 프린트안에 넣으면 세션없이 바로 프린트할 수 있다.
# shape이 뭐냐확인
# tf.shape(t).eval()
# shape도 하나의 operator라서 세션런으로 실행을 해야한다. 
mat1 = tf.constant([[1,2],[3,4]])
mat2 = tf.constant([[1],[2]])
print(tf.shape(mat1).eval())
print(tf.shape(mat2).eval())
print(mat1.eval())
print(mat2.eval())
print((mat1 * mat2).eval())

[2 2]
[2 1]
[[1 2]
 [3 4]]
[[1]
 [2]]
[[1 2]
 [6 8]]


In [ ]:
# .이 있으면 float
# reduce_mean은 평균을 내는 operation이다.

In [24]:
x = [[1.,2],[3,4]]
tf.reduce_mean(x).eval()

2.5

In [25]:
#axis = 0 --> 열
#axis = 1 --> row 
# 가장 바깥쪽 덩어리가 0, 그 다음 껍데기 기준으로 평균해라 axis=1
# 가장 안쪽만 하고 싶으면 axis= -1 할 수 있다. 
# 항상 같은 인덱스끼리 하는 거야 계산은

In [26]:
x = [[1.,2],[3,4]]
tf.reduce_sum(x, axis = 0).eval()

array([4., 6.], dtype=float32)

In [27]:
x = [[1.,2],[3,4]]
tf.reduce_sum(x, axis = 1).eval()

array([3., 7.], dtype=float32)

In [30]:
tf.reduce_mean(tf.reduce_sum(x, axis = 1).eval()).eval()

5.0

In [31]:
# time series(시계열 분석 흐름) -->  axis = 0
# 크로스섹셔널 --> axis = 1
# axis를 조절해가면서 내가 보고싶은 insight

In [33]:
# argmax 가장 큰 값의 index를 뽑아내기

In [32]:
x = [[0,1,2,],
     [3,4,5]]
tf.argmax(x, axis = 0).eval()
# axis를 기준으로 비교해서 가장 큰 index를 반환해준다.
# 사례로 들면 수익률이 상위 10%이 들 확률이 주어진다. 총 10개의 확률값이 주어진다. 
# 2000개의 기업을 볼 수 없다.

array([1, 1, 1], dtype=int64)

In [ ]:
# reshape을 하고 싶다면? tf.reshaped()

In [34]:
x = [1,2,3,4,5,6,7,8,9]
tf.reshape(x,[3,3]).eval()
# 사진 이미지가 쭉 숫자로 되어 있는 걸 28,28로 나타내는 것이 그림판이다. 
# 이미지처리할떄 굉장히 많이 사용한다. 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# tf.one_hot()

In [37]:
t = tf.one_hot([[0],[1],[2],[3]], depth = 4).eval()
# 하나는 0을 넣고 나머지는 1을 넣어라 
# 나중에 분류할때 이거는 1번클래스야 2번클래스야가 아니라
# one_hot인코딩으로 나누는 것이다. 
# 2차원을 주면 3차원을 넣어준다. 

In [40]:
# tf.reshape(t,[-1,4]).eval() 한차원을 빼주는 방법

In [39]:
t = tf.reshape(t,[-1,4]).eval()

In [43]:
sess = tf.InteractiveSession()
a = tf.one_hot([[0],[1],[2],[3]],depth = 4).eval()
tf.reshape(a, shape=[-1,4]).eval()


c:\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\client\session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [44]:
# 타입 변경 - tf.cast(데이터, 변환타입)

In [45]:
tf.cast([1.8,3.9,3.02,309.3], tf.int32).eval()

array([  1,   3,   3, 309])

In [46]:
a = tf.cast([True, False, 1==1, 1!=1], tf.float32).eval()
tf.reduce_mean(a).eval()

0.5

In [47]:
# 불리언 타입을 숫자형식으로 하는게 더 좋다. 
# 그걸 1과 0으로 변환하고 1을 다 더하고 전체갯수로 나누면 accuracy를 구할 수 있다. 
# 불리언 캐스팅하고 이거 리듀스 mean하면 평균값이 나온다.

In [48]:
# 차원 stack하기 - tf.stack([x,y,z])  기본적으로 vertical

In [49]:
x = [1,4]
y = [2,5]
z = [3,6]
tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
# tf.ones_like(x) 하면 x와 똑같은shape에 1로 채워진 것이 채워진다.
# tf.zeros_like(x) 하면 x와 똑같은shape에 0로 채워진 것이 채워진다.

In [58]:
x = [[1,2,3],[4,5,6],[7,8,9]]
tf.ones_like(x).eval()
tf.zeros_like(x).eval()
tf.shape(x).eval()


TypeError: list indices must be integers or slices, not tuple

TypeError: list indices must be integers or slices, not tuple